services:
  db:
    image: postgres
    container_name: mc_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5434:5432
    networks:
      mc_network: 
        aliases:
          - mc_database
  app:
    container_name: mc_service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    volumes:
      - ./src:/home/app/src
    links:
      - db
    environment:
      DATABASE_URL: ${DATABASE_DOCKER_URL}
    networks:
      mc_network:
        aliases:
          - mc_service
networks:
  mc_network:
    name: MascotasGo_Network
    driver: bridge
    ipam:
      driver: default
    external: true